spring.application.name=leoadmin

spring.datasource.url=jdbc:postgresql://localhost:5432/leoadmin
spring.datasource.username=postgres
spring.datasource.password=pe11060319

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect